name: chistoplaner
description: "App for scheduling cleaning and monitoring cleaning frequency."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  intl: ^0.18.1
  talker_flutter: ^4.1.3
  go_router: ^13.2.5
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/home_icons/

  fonts:
    - family: Rostov
      fonts:
        - asset: assets/fonts/Rostov.ttf
    - family: Mak
      fonts:
        - asset: assets/fonts/MAK.otf
    - family: Frenchpress
      fonts:
        - asset: assets/fonts/frenchpress.ttf
flutter_intl:
  enabled: true
